name: Push the Docker image

on: [ push, workflow_dispatch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag krishhi/flask-github-actions-app

    - name: Push into Docker Hub
      run: docker push krishhi/flask-github-actions-app
