name: secrets

on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: configure aws cli credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: us-east-2

        - name: List S3 buckets
          run: aws s3api list-buckets

        - name: Copy files to the test website with the AWS CLI
          run: aws s3 sync . s3://my-s3-test-website-bucket
