name: uptime monitor

on:
  schedule:
      - cron: '0 */6 * * *'

jobs:
  ping-state:
      runs-on: ubuntu-latest
      name: uptime check
      steps:
      - name: ping site
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://github.com"
          expected-statuses: "200,301"
